# Generated by Django 4.2.6 on 2023-11-11 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_profile_delete_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('transmission', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Car_Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('mileage', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('listing_date', models.DateField()),
                ('link_to_buyer', models.URLField(blank=True, db_index=True, max_length=256, unique=True, verbose_name='Link')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.carmodel')),
            ],
        ),
    ]
