# Generated by Django 4.2.6 on 2023-11-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_carmodel_car_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_listing',
            name='makes',
            field=models.CharField(default='Hi', max_length=20),
        ),
    ]
