# Generated by Django 4.2.6 on 2023-11-21 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_carmodel_fuel_type_alter_carmodel_transmission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_listing',
            name='makes',
        ),
    ]
