# Generated by Django 4.2.6 on 2023-11-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_remove_carmodel_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_listing',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
