# Generated by Django 4.2.6 on 2023-12-02 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_car_listing_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_listing',
            old_name='link_to_buyer',
            new_name='Link_to_buyer',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='link_to_image',
            new_name='Link_to_image',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='listing_date',
            new_name='Listing_date',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='make',
            new_name='Make',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='mileage',
            new_name='Mileage',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='car_model',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='price',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='source',
            new_name='Source',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='year',
            new_name='Year',
        ),
    ]
