# Generated by Django 4.2.6 on 2023-12-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_rename_link_to_buyer_car_listing_link_to_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listing',
            name='Model',
            field=models.CharField(max_length=50),
        ),
    ]
