# Generated by Django 4.2.6 on 2023-12-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_car_listing_link_to_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_listing',
            name='Link_to_buyer',
            field=models.URLField(blank=True, db_index=True, max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='car_listing',
            name='Link_to_image',
            field=models.URLField(blank=True, db_index=True, max_length=256, verbose_name='Link'),
        ),
    ]
