# Generated by Django 4.2.6 on 2023-12-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_car_listing_link_to_buyer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_listing',
            old_name='Link_to_buyer',
            new_name='link_to_buyer',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Link_to_image',
            new_name='link_to_image',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Listing_date',
            new_name='listing_date',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Mileage',
            new_name='mileage',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Source',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='car_listing',
            old_name='Year',
            new_name='year',
        ),
    ]
